### ISSUE TITLE
Strange behavior with `split:swapactiveworkspaces`

### ISSUE THREAD

**Issue by tiecia** [shezdy/hyprsplit#27]
First off, thank you for this hyprland plugin. I've been using it for a few months now and love it.

I am experiencing some strange behavior with the `split:swapactiveworkspaces` dispatcher with stacked monitors. I have created some sketches below of some of the behavior I am experiencing.

First, if I have three windows, two on the top monitor and 1 on the bottom monitor. The two windows sometimes swap positions after swapping the workspaces.
![image](https://github.com/user-attachments/assets/d8f7b378-9b9f-4d28-b6fb-3eab16def089)

Second, if I have four windows open, two on each monitor, sometimes some of the windows switch split directions like the diagram shows. Or sometimes both sets of windows swap positions but stay in the same split orientation.
![image](https://github.com/user-attachments/assets/280fac32-8e28-4430-98d2-89f54af6abee)

The reason I say sometimes is because there is no clear pattern as to when this strange behavior happens. It sometimes seems to depend on which workspace is active before the swap, but this is unclear.

There are many more permutations of strange behavior and if I start to add even more windows then things get even worse.

Please let me know if you would like some more information, I am happy to provide it.

**Comment by shezdy** [comment]
This happens because split:swapactiveworkspaces moves windows between each workspace the same way that movetoworkspace would move windows (layout is not preserved, each is treated a 'new' window on the workspace).

With master layout this method has good results for me most of the time, but with dwindle layout the splits seem to be unpredictable. I tried fixing this in the past by moving the actual workspaces between monitors like vanilla Hyprland, then swapping workspace ids, but changing workspace ids causes windows to disappear.

I might look it into it more in the future, not sure.

**Comment by shezdy** [comment]
layout is preserved for master and dwindle now. plugin layouts will still use the old method for now, compatibility can be added for them individually.
