### ISSUE TITLE
Feature Request: Persistent pre-created workspaces

### ISSUE THREAD

**Issue by leierr** [shezdy/hyprsplit#29]
It would be awesome to port the following settings from `split-monitor-workspaces` to this fork

plugin:split-monitor-workspaces:enable_persistent_workspaces = true

**Comment by leierr** [comment]
Hey @shezdy! I know this might be asking a lot (especially since I can’t write a line of C++ code), but is there any chance you could backport it to [revision "refs/tags/v0.41.2"?](https://github.com/shezdy/hyprsplit/releases/tag/v0.41.2) ? Or am I completely misunderstanding how git works? 😅

I’m stuck using a couple of revisions behind because NixOS stable still uses an older version of Hyprland. I guess I’ll just have to wait for Hyprland 0.43! 😛

**Comment by shezdy** [comment]
i created a branch `backport-0.41.2` that should fix the plugin building with hyprland 0.41.2. set the plugin to use that branch and it will hopefully build!

**Comment by leierr** [comment]
Everything built and worked perfectly—thank you so much! You really made my day. 😄

That said, I believe this could prompt a slightly larger change. The main reason I wanted pre-created workspaces was to integrate with other plugins that switch to those workspaces instead of creating their own, which is guaranteed to be out of the order this plugin maintains.

I think we should consider adding a feature for this plugin to take ownership of its own workspaces. In a previous setup, I implemented something similar in bash by using each monitor's serial number (e.g., 0x000021BD → 8637) and adding workspace IDs (8637 + 1, 2, 3, etc.) for that monitor. This ensured that each monitor had its own unique set of workspaces. If a monitor disconnected, I would set persistent:false to move the workspaces with open windows to an active monitor and let the others disappear.

Currently, with workspaces being permanently persistent, disconnecting a monitor becomes tricky because you have to manually destroy the workspaces.

What do you think—up for the challenge? 😅

**Comment by shezdy** [comment]
When disconnecting a monitor the plugin should be setting persistent to false for the disconnected workspaces, it was working when I tested it?

Workspaces that contain windows will continue to exist and be moved to a different monitor. You will need to use `split:grabroguewindows` to grab those (then the workspaces will be destroyed since they are no longer persistent).

While technically possible to grab the windows automatically on monitor disconnect, it is very hard to get it working while preserving layout in certain cases (eg when waking from suspend). I had a semi-functional implementation at one point but I think it would require deeper changes in Hyprland for the plugin to reasonably be able to restore layout in certain cases where it is necessary, hence the band aid fix of `split:grabroguewindows`

**Comment by leierr** [comment]
Damn, my bad. I just tested it, and everything worked as expected. The workspaces moved to a random monitor, and the ones with no windows got deleted. Even better, when I plugged my monitor back in, the workspaces moved back, which is awesome.

I'll report back after testing on my laptop, which I dock and undock in various places throughout the day. Exciting stuff—thanks again! :sun_with_face:
